"""
pygeovision.insar.slc.snaphu
==============================
SNAPHU phase unwrapping wrapper.

SNAPHU (Statistical-Cost Network-Flow Algorithm for Phase Unwrapping)
is the standard tool for InSAR phase unwrapping. It solves the 2-pi
ambiguity inherent in wrapped interferometric phase.

Install:
    conda install -c conda-forge snaphu
    or: sudo apt install snaphu       # Ubuntu/Debian
    or: brew install snaphu           # macOS via Homebrew

Typical workflow:
    1. SNAP Goldstein filtering   -> wrapped phase .img file
    2. SNAP SnaphuExport          -> creates snaphu.conf + wrapped.img
    3. SnaphuUnwrapper.run()      -> calls snaphu CLI
    4. SNAP SnaphuImport          -> re-reads unwrapped phase into SNAP
    5. phase_to_displacement()    -> converts to metres
"""
from __future__ import annotations

import logging
import os
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

logger = logging.getLogger("pygeovision.insar.slc.snaphu")


# ── Configuration dataclass ───────────────────────────────────────────────────

@dataclass
class SnaphuConfig:
    """
    SNAPHU configuration parameters.

    Mirrors the snaphu.conf file written by SNAP's SnaphuExport operator.

    Parameters
    ----------
    stat_cost_mode : str
        Statistical cost mode. DEFO for deformation, SMOOTH for smooth surfaces.
    init_method : str
        Phase unwrapping initialisation. MCF (Minimum Cost Flow) or MST.
    n_procs : int
        Number of parallel processes for tile-based unwrapping.
    tile_rows : int
        Number of tile rows (larger = less memory per tile).
    tile_cols : int
        Number of tile columns.
    row_overlap : int
        Overlap between tile rows in pixels (recommended >= 200).
    col_overlap : int
        Overlap between tile columns in pixels.
    coh_threshold : float
        Coherence threshold below which pixels are masked (0–1).
    """
    stat_cost_mode: str   = "DEFO"
    init_method:    str   = "MCF"
    n_procs:        int   = 4
    tile_rows:      int   = 10
    tile_cols:      int   = 10
    row_overlap:    int   = 200
    col_overlap:    int   = 200
    coh_threshold:  float = 0.3

    def to_conf_string(
        self,
        wrapped_file:     str,
        unwrapped_file:   str,
        coherence_file:   str,
        n_lines:          int,
        line_length:      int,
    ) -> str:
        """Generate the content of a snaphu.conf file."""
        return f"""# snaphu.conf generated by PyGeoVision
# https://github.com/appiahkubis14/PyGeoVision

STATCOSTMODE   {self.stat_cost_mode}
INITMETHOD     {self.init_method}

INFILE         {wrapped_file}
COHERFILE      {coherence_file}
OUTFILE        {unwrapped_file}

LINELENGTH     {line_length}
NLINES         {n_lines}
NCORRLOOKS     1
INFILEFORMAT   COMPLEX_DATA
OUTFILEFORMAT  FLOAT_DATA

NTILEROW       {self.tile_rows}
NTILECOL       {self.tile_cols}
ROWOVRLP       {self.row_overlap}
COLOVRLP       {self.col_overlap}
NPROC          {self.n_procs}

CORR_THRESHOLD {self.coh_threshold}
"""


# ── Main unwrapper ────────────────────────────────────────────────────────────

@dataclass
class UnwrappingResult:
    """Result of SNAPHU phase unwrapping."""
    unwrapped_path: str                    # Path to unwrapped phase .img
    wrapped_path:   str                    # Input wrapped phase path
    coherence_path: str                    # Coherence used for masking
    n_lines:        int   = 0
    line_length:    int   = 0
    masked_fraction: float = 0.0           # Fraction of pixels masked by coherence
    stats:          Dict  = field(default_factory=dict)


class SnaphuUnwrapper:
    """
    Wrapper around the SNAPHU phase unwrapping CLI.

    Works with the output of SNAP's SnaphuExport operator. The export
    creates a directory containing:
        - snaphu.conf        : configuration file with image dimensions
        - *.snaphu.img       : wrapped phase in SNAPHU binary format
        - *.coh              : coherence file (for masking)

    Parameters
    ----------
    snaphu_exe : str, optional
        Path to snaphu executable. Defaults to 'snaphu' on PATH.
    config : SnaphuConfig, optional
        Unwrapping parameters. Defaults to sensible values for deformation.
    """

    def __init__(
        self,
        snaphu_exe: Optional[str] = None,
        config:     Optional[SnaphuConfig] = None,
    ) -> None:
        self.exe    = snaphu_exe or shutil.which("snaphu") or "snaphu"
        self.config = config or SnaphuConfig()
        self._available: Optional[bool] = None

    @property
    def available(self) -> bool:
        if self._available is None:
            self._available = shutil.which(self.exe) is not None or Path(self.exe).exists()
        return self._available

    def run(
        self,
        snaphu_export_dir: str,
        output_dir:        Optional[str] = None,
    ) -> UnwrappingResult:
        """
        Run SNAPHU on the output of SNAP's SnaphuExport operator.

        Parameters
        ----------
        snaphu_export_dir : str
            Directory created by SNAP's SnaphuExport step.
            Must contain a snaphu.conf and at least one .snaphu.img file.
        output_dir : str, optional
            Where to write the unwrapped phase. Defaults to snaphu_export_dir.

        Returns
        -------
        UnwrappingResult
        """
        if not self.available:
            raise RuntimeError(
                "snaphu executable not found.\n"
                "Install: conda install -c conda-forge snaphu\n"
                "    or:  sudo apt install snaphu\n"
                "    or:  https://web.stanford.edu/group/radar/softwareandlinks/sw/snaphu/"
            )

        snap_dir   = Path(snaphu_export_dir)
        out_dir    = Path(output_dir) if output_dir else snap_dir
        out_dir.mkdir(parents=True, exist_ok=True)

        # ── Find files in SNAP export directory ───────────────────────────
        conf_file     = self._find_file(snap_dir, "snaphu.conf")
        wrapped_file  = self._find_file(snap_dir, "*.snaphu.img", "*.img")
        coh_file      = self._find_file(snap_dir, "*.coh", "*.coherence.img")

        if not conf_file or not wrapped_file:
            raise FileNotFoundError(
                f"snaphu.conf or wrapped phase .img not found in {snap_dir}.\n"
                f"Files present: {[f.name for f in snap_dir.iterdir()]}"
            )

        # ── Parse image dimensions from conf ──────────────────────────────
        n_lines, line_length = self._parse_dimensions(conf_file)
        logger.info(
            "Unwrapping: %d lines × %d pixels, coh_threshold=%.2f",
            n_lines, line_length, self.config.coh_threshold,
        )

        # ── Write PyGeoVision's own conf (overrides SNAP defaults) ────────
        unwrapped_file = str(out_dir / (Path(wrapped_file).stem + "_unwrapped.img"))
        pgv_conf = str(out_dir / "pygeovision_snaphu.conf")
        coh_for_conf = coh_file or ""
        Path(pgv_conf).write_text(
            self.config.to_conf_string(
                wrapped_file   = wrapped_file,
                unwrapped_file = unwrapped_file,
                coherence_file = coh_for_conf,
                n_lines        = n_lines,
                line_length    = line_length,
            )
        )

        # ── Run SNAPHU ────────────────────────────────────────────────────
        cmd = [self.exe, "-f", pgv_conf]
        logger.info("Running: %s", " ".join(cmd))

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=str(snap_dir),
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"SNAPHU failed (exit {result.returncode}).\n"
                f"STDERR:\n{result.stderr[-2000:]}\n"
                f"STDOUT:\n{result.stdout[-1000:]}"
            )

        logger.info("SNAPHU unwrapping complete: %s", unwrapped_file)

        # ── Compute coherence mask statistics ─────────────────────────────
        masked_frac = self._compute_masked_fraction(
            n_lines, line_length, coh_file
        )

        return UnwrappingResult(
            unwrapped_path   = unwrapped_file,
            wrapped_path     = wrapped_file,
            coherence_path   = coh_file or "",
            n_lines          = n_lines,
            line_length      = line_length,
            masked_fraction  = masked_frac,
            stats={
                "snaphu_conf": pgv_conf,
                "log":         result.stdout[-500:],
            },
        )

    def run_from_rasters(
        self,
        wrapped_phase: np.ndarray,
        coherence:     np.ndarray,
        output_dir:    str,
    ) -> np.ndarray:
        """
        Unwrap a phase array directly (bypasses SNAP export format).

        Writes temporary binary files in SNAPHU format, runs unwrapping,
        and returns the unwrapped phase as a numpy array.

        Parameters
        ----------
        wrapped_phase : np.ndarray
            2D array of wrapped phase in radians (float32).
        coherence : np.ndarray
            2D array of coherence values (float32, 0–1).
        output_dir : str
            Working directory for temporary files.

        Returns
        -------
        np.ndarray
            2D unwrapped phase array in radians.
        """
        if not self.available:
            raise RuntimeError("snaphu not found. Install: conda install -c conda-forge snaphu")

        work_dir = Path(output_dir)
        work_dir.mkdir(parents=True, exist_ok=True)

        n_lines, line_length = wrapped_phase.shape

        # Write wrapped phase as SNAPHU COMPLEX_DATA
        # SNAPHU expects interleaved complex: [real, imag] pairs
        # We encode phase as e^(i*phi) = cos(phi) + i*sin(phi)
        real_part = np.cos(wrapped_phase).astype(np.float32)
        imag_part = np.sin(wrapped_phase).astype(np.float32)
        complex_data = np.empty(n_lines * line_length * 2, dtype=np.float32)
        complex_data[0::2] = real_part.ravel()
        complex_data[1::2] = imag_part.ravel()

        wrapped_bin    = str(work_dir / "wrapped.img")
        coherence_bin  = str(work_dir / "coherence.img")
        unwrapped_bin  = str(work_dir / "unwrapped.img")

        complex_data.tofile(wrapped_bin)
        coherence.astype(np.float32).ravel().tofile(coherence_bin)

        pgv_conf = str(work_dir / "snaphu.conf")
        Path(pgv_conf).write_text(
            self.config.to_conf_string(
                wrapped_file   = wrapped_bin,
                unwrapped_file = unwrapped_bin,
                coherence_file = coherence_bin,
                n_lines        = n_lines,
                line_length    = line_length,
            )
        )

        r = subprocess.run(
            [self.exe, "-f", pgv_conf],
            capture_output=True, text=True, cwd=str(work_dir),
        )
        if r.returncode != 0:
            raise RuntimeError(f"SNAPHU failed:\n{r.stderr[-1500:]}")

        # Read back unwrapped phase (FLOAT_DATA = float32)
        unwrapped_flat = np.fromfile(unwrapped_bin, dtype=np.float32)
        if unwrapped_flat.size != n_lines * line_length:
            raise ValueError(
                f"Unexpected unwrapped output size: "
                f"{unwrapped_flat.size} vs expected {n_lines * line_length}."
            )

        return unwrapped_flat.reshape(n_lines, line_length)

    # ── Helpers ───────────────────────────────────────────────────────────

    @staticmethod
    def _find_file(directory: Path, *patterns: str) -> Optional[str]:
        """Find first matching file in directory."""
        for pattern in patterns:
            matches = list(directory.glob(pattern))
            if matches:
                return str(matches[0])
        return None

    @staticmethod
    def _parse_dimensions(conf_file: str) -> Tuple[int, int]:
        """Parse NLINES and LINELENGTH from a snaphu.conf file."""
        text   = Path(conf_file).read_text()
        n_line = re.search(r"^\s*NLINES\s+(\d+)", text, re.MULTILINE)
        n_col  = re.search(r"^\s*LINELENGTH\s+(\d+)", text, re.MULTILINE)
        n_lines      = int(n_line.group(1)) if n_line else 0
        line_length  = int(n_col.group(1))  if n_col  else 0
        if not n_lines or not line_length:
            raise ValueError(
                f"Could not parse NLINES / LINELENGTH from {conf_file}. "
                f"File contents:\n{text[:500]}"
            )
        return n_lines, line_length

    def _compute_masked_fraction(
        self,
        n_lines:     int,
        line_length: int,
        coh_file:    Optional[str],
    ) -> float:
        if not coh_file or not Path(coh_file).exists():
            return 0.0
        try:
            coh = np.fromfile(coh_file, dtype=np.float32)
            if coh.size == n_lines * line_length:
                masked = np.sum(coh < self.config.coh_threshold)
                return float(masked) / coh.size
        except Exception:
            pass
        return 0.0


# ── Convenience function ──────────────────────────────────────────────────────

def unwrap_phase(
    snaphu_export_dir: str,
    output_dir:        Optional[str] = None,
    stat_cost_mode:    str = "DEFO",
    n_procs:           int = 4,
    coh_threshold:     float = 0.3,
) -> UnwrappingResult:
    """
    Convenience wrapper: unwrap a SNAP SnaphuExport directory.

    Parameters
    ----------
    snaphu_export_dir : str
        Directory from SNAP's SnaphuExport step.
    output_dir : str, optional
        Where to write unwrapped phase. Defaults to snaphu_export_dir.
    stat_cost_mode : str
        'DEFO' for deformation mapping, 'SMOOTH' for smooth scenes.
    n_procs : int
        Number of parallel SNAPHU processes.
    coh_threshold : float
        Coherence threshold for pixel masking.

    Returns
    -------
    UnwrappingResult
    """
    cfg      = SnaphuConfig(
        stat_cost_mode=stat_cost_mode,
        n_procs=n_procs,
        coh_threshold=coh_threshold,
    )
    unwrapper = SnaphuUnwrapper(config=cfg)
    return unwrapper.run(snaphu_export_dir, output_dir)
